export const GET = 'GET'
export const POST = 'POST'
export const DELETE = 'DELETE'
export const PUT = 'PUT'
export const REQUEST_STARTED = 'REQUEST_STARTED'
export const REQUEST_SUCCEDED = 'REQUEST_SUCCEDED'
export const REQUEST_FAILED = 'REQUEST_FAILED'
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ADMIN_PRODUCTS_SUCCEEDED = 'GET_ADMIN_PRODUCTS_SUCCEEDED';
export const ADMIN_DELETED_PRODUCT = 'ADMIN_DELETED_PRODUCT';
export const GET_ADMIN_PRODUCT_DETAILS_SUCCEEDED = 'GET_ADMIN_PRODUCT_DETAILS_SUCCEEDED';
export const GET_ADMIN_OPTION_TYPES_SUCCEEDED = 'GET_ADMIN_OPTION_TYPES_SUCCEEDED';

export const OPTION_TYPE = 'OptionType'
export const CATEGORY = 'Category'
export const BRAND = 'Brand'
export const PRODUCT_PROPERTY = 'Product Property'